"""Pydantic schemas for API requests and responses."""

from app.shared.schemas.tenant import (
    TenantProfileUpdate,
    TenantResponse,
    TenantListItem,
    TenantPublicProfile,
)
from app.shared.schemas.appointment import (
    AppointmentBase,
    AppointmentCreate,
    AppointmentUpdate,
    AppointmentCancel,
    AppointmentResponse,
    AppointmentListItem,
    VisitBase,
    VisitCreate,
    VisitUpdate,
    VisitResponse,
    VisitListItem,
)
from app.shared.schemas.doctor import (
    DoctorProfileResponse,
    DoctorProfileUpdate,
    DoctorDegreeBase,
    DoctorDegreeCreate,
    DoctorDegreeUpdate,
    DoctorDegreeResponse,
    DoctorTrainingBase,
    DoctorTrainingCreate,
    DoctorTrainingUpdate,
    DoctorTrainingResponse,
)
from app.shared.schemas.patient import (
    PatientBase,
    PatientCreate,
    PatientUpdate,
    PatientResponse,
    PatientListItem,
    PatientSearchResult,
    PatientTagBase,
    PatientTagCreate,
    PatientTagUpdate,
    PatientTagResponse,
    PatientDiagnosisBase,
    PatientDiagnosisCreate,
    PatientDiagnosisUpdate,
    PatientDiagnosisResponse,
)
from app.shared.schemas.prescription import (
    PrescriptionItemBase,
    PrescriptionItemCreate,
    PrescriptionItemUpdate,
    PrescriptionItemResponse,
    PrescriptionBase,
    PrescriptionCreate,
    PrescriptionUpdate,
    PrescriptionResponse,
    PrescriptionListItem,
)
from app.shared.schemas.payment import (
    PaymentBase,
    PaymentCreate,
    PaymentUpdate,
    PaymentResponse,
    PaymentListItem,
    BkashPaymentCreate,
    BkashPaymentExecute,
    BkashPaymentQuery,
    BkashRefundRequest,
    BkashPaymentResponse,
    InvoiceBase,
    InvoiceCreate,
    InvoiceUpdate,
    InvoiceResponse,
    InvoiceListItem,
    PaymentSummary,
)
from app.shared.schemas.symptom import (
    SymptomBase,
    SymptomCreate,
    SymptomUpdate,
    SymptomResponse,
    SymptomListItem,
    SymptomWithAliases,
    SymptomSearchResult,
    SymptomAliasBase,
    SymptomAliasCreate,
    SymptomAliasUpdate,
    SymptomAliasResponse,
    MedicineSymptomMappingBase,
    MedicineSymptomMappingCreate,
    MedicineSymptomMappingUpdate,
    MedicineSymptomMappingResponse,
)
from app.shared.schemas.medicine import (
    MedicineBase,
    MedicineCreate,
    MedicineUpdate,
    MedicineResponse,
    MedicineListItem,
    MedicineSearchResult,
    MedicineAliasBase,
    MedicineAliasCreate,
    MedicineAliasUpdate,
    MedicineAliasResponse,
    MedicineWithSymptoms,
)
from app.shared.schemas.dashboard import (
    DateRangeFilter,
    TrendData,
    OverviewStats,
    FinancialAnalytics,
    RevenueByMethod,
    PatientAnalytics,
    PatientDemographics,
    AgeGroupDistribution,
    TopDiagnosis,
    AppointmentAnalytics,
    AppointmentByStatus,
    AppointmentByType,
    VisitAnalytics,
    VisitByType,
    TopChiefComplaint,
    PrescriptionAnalytics,
    PrescriptionByStatus,
    TopMedicine,
)
from app.shared.schemas.integration import (
    IntegrationProviderResponse,
    IntegrationProviderListItem,
    TenantIntegrationCreate,
    TenantIntegrationUpdate,
    TenantIntegrationResponse,
    TenantIntegrationListItem,
    IntegrationTestRequest,
    IntegrationTestResponse,
    IntegrationLogResponse,
    IntegrationLogListItem,
    SendSMSRequest,
    SendEmailRequest,
    SendOperationResponse,
)

__all__ = [
    # Tenant/Clinic
    "TenantProfileUpdate",
    "TenantResponse",
    "TenantListItem",
    "TenantPublicProfile",
    # Appointments
    "AppointmentBase",
    "AppointmentCreate",
    "AppointmentUpdate",
    "AppointmentCancel",
    "AppointmentResponse",
    "AppointmentListItem",
    # Visits
    "VisitBase",
    "VisitCreate",
    "VisitUpdate",
    "VisitResponse",
    "VisitListItem",
    # Doctor Profile
    "DoctorProfileResponse",
    "DoctorProfileUpdate",
    # Doctor Degrees
    "DoctorDegreeBase",
    "DoctorDegreeCreate",
    "DoctorDegreeUpdate",
    "DoctorDegreeResponse",
    # Doctor Trainings
    "DoctorTrainingBase",
    "DoctorTrainingCreate",
    "DoctorTrainingUpdate",
    "DoctorTrainingResponse",
    # Patients
    "PatientBase",
    "PatientCreate",
    "PatientUpdate",
    "PatientResponse",
    "PatientListItem",
    "PatientSearchResult",
    # Patient Tags
    "PatientTagBase",
    "PatientTagCreate",
    "PatientTagUpdate",
    "PatientTagResponse",
    # Patient Diagnoses
    "PatientDiagnosisBase",
    "PatientDiagnosisCreate",
    "PatientDiagnosisUpdate",
    "PatientDiagnosisResponse",
    # Symptoms
    "SymptomBase",
    "SymptomCreate",
    "SymptomUpdate",
    "SymptomResponse",
    "SymptomListItem",
    "SymptomWithAliases",
    "SymptomSearchResult",
    # Symptom Aliases
    "SymptomAliasBase",
    "SymptomAliasCreate",
    "SymptomAliasUpdate",
    "SymptomAliasResponse",
    # Medicines
    "MedicineBase",
    "MedicineCreate",
    "MedicineUpdate",
    "MedicineResponse",
    "MedicineListItem",
    "MedicineSearchResult",
    "MedicineWithSymptoms",
    # Medicine Aliases
    "MedicineAliasBase",
    "MedicineAliasCreate",
    "MedicineAliasUpdate",
    "MedicineAliasResponse",
    # Medicine-Symptom Mappings
    "MedicineSymptomMappingBase",
    "MedicineSymptomMappingCreate",
    "MedicineSymptomMappingUpdate",
    "MedicineSymptomMappingResponse",
    # Prescription Items
    "PrescriptionItemBase",
    "PrescriptionItemCreate",
    "PrescriptionItemUpdate",
    "PrescriptionItemResponse",
    # Prescriptions
    "PrescriptionBase",
    "PrescriptionCreate",
    "PrescriptionUpdate",
    "PrescriptionResponse",
    "PrescriptionListItem",
    # Payments
    "PaymentBase",
    "PaymentCreate",
    "PaymentUpdate",
    "PaymentResponse",
    "PaymentListItem",
    # bKash
    "BkashPaymentCreate",
    "BkashPaymentExecute",
    "BkashPaymentQuery",
    "BkashRefundRequest",
    "BkashPaymentResponse",
    # Invoices
    "InvoiceBase",
    "InvoiceCreate",
    "InvoiceUpdate",
    "InvoiceResponse",
    "InvoiceListItem",
    "PaymentSummary",
    # Dashboard
    "DateRangeFilter",
    "TrendData",
    "OverviewStats",
    "FinancialAnalytics",
    "RevenueByMethod",
    "PatientAnalytics",
    "PatientDemographics",
    "AgeGroupDistribution",
    "TopDiagnosis",
    "AppointmentAnalytics",
    "AppointmentByStatus",
    "AppointmentByType",
    "VisitAnalytics",
    "VisitByType",
    "TopChiefComplaint",
    "PrescriptionAnalytics",
    "PrescriptionByStatus",
    "TopMedicine",
    # Integration Providers
    "IntegrationProviderResponse",
    "IntegrationProviderListItem",
    # Tenant Integrations
    "TenantIntegrationCreate",
    "TenantIntegrationUpdate",
    "TenantIntegrationResponse",
    "TenantIntegrationListItem",
    # Integration Tests
    "IntegrationTestRequest",
    "IntegrationTestResponse",
    # Integration Logs
    "IntegrationLogResponse",
    "IntegrationLogListItem",
    # Send Operations
    "SendSMSRequest",
    "SendEmailRequest",
    "SendOperationResponse",
]
